spring.application.name=chatapp
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis-17830.c245.us-east-1-3.ec2.cloud.redislabs.com}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:17830}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:oWXiRD2VyeMF1AlBCMAL0iCQjF0ILsfc}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:false}
